language: node_js
node_js:
  - "14"
# Distro of Linux
dist: trusty
services:
    - postgresql
env:
    - NODE_ENV=ci
# Save a directory for future builds instead of recreating
# After a build and before install it copies node_modules
cache: 
    directories:
        - node_modules
# How to execute the project into that virtual machine
install:
    - npm install
# Test
script: 
    # Nohup: If the shell is closed, don't kill anything this command creates
    # npm run start: run the server (obviously)
    # Run this command in a subshell in background
    - nohup npm run start &
    - sleep 3 # This avoid the test to try to access to the application before it actually starts
    - npm run test
